package com.brainiac.model;

public enum Action {
    NONE, BUILD_TOWER, BUILD_BLOCKAGE, UPGRADE_TOWER ,UPGRADE_TOWER_ELF, UPGRADE_TOWER_MAN, UPGRADE_TOWER_DWARF, UPGRADE_TOWER_HOBBIT, UPGRADE_BLOCKAGE,
    UPGRADE_BLOCKAGE_MAN, UPGRADE_BLOCKAGE_ELF, UPGRADE_BLOCKAGE_DWARF, UPGRADE_BLOCKAGE_HOBBIT, UPGRADE_FIRE_RATE, UPGRADE_DAMAGE, UPGRADE_RANGE
}
